name: 🚀 Deploy naar Mijndomein

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛰️ Haal code op
        uses: actions/checkout@v4

      - name: 📂 Upload via FTP
        uses: ArielMejiaDev/ftp-deploy@v3.0.0
        with:
          server: ftp.flip2trip.nl
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          # We proberen nu het pad zonder enige extra tekens:
          local_dir: .
          remote_dir: ./httpdocs
          delete: false
