name: 🚀 Deploy naar Mijndomein

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛰️ Haal code op
        uses: actions/checkout@v4

      - name: 📂 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.flip2trip.nl
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # We proberen nu het relatieve pad zonder slashes aan het begin
          server-dir: ./httpdocs/
          security: loose
          timeout: 60000
